# **Sesión 3: Procesamiento Avanzado de Imágenes** ⚙️🖼️

## **Librerías**

In [8]:
import cv2
import os
import copy
import imageio
from typing import List
import numpy as np

## **Apartado B:** Detección de lineas rectas
El objetivo de este apartado es la detección de líneas y bordes en las imágenes de la carpeta `data`.
1. **Tarea B.1.** Aplique `cv2.Canny()` a las imágenes de trabajo ajustando los hiperparámetros.
3. **Tarea B.2.** Implemente la función `draw_lines()` para pintar las líneas sobre las imágenes.
4. **Tarea B.3.** Aplique Hough con `cv2.HoughLinesP()` a las imágenes de trabajo para extraer líneas y afine los hiperparámetros.
5. **Problema B.1.** Repita el procedimiento para extraer las líneas de las dos imágenes restantes.

### **NOTA**
Podéis usar el mismo formato de guardado de resultados y nomenclatura que en partA o hacer uso de la funcion `show_image()` del Lab 2. Usad las herramientas con las que os sintáis más cómodos

In [9]:
folder_name = "partB"
folder_path = os.path.join("../data", folder_name)
os.makedirs(folder_path, exist_ok=True)

In [10]:
import glob

# This initial part is to highlight that cv2.imshow() and cv2.imwrite() works well with previous BGR conversion
def imageio_load_images(filenames: List) -> List:
    '''
    Load images using imageio.imread function (RGB)
    '''
    return [imageio.imread(filename) for filename in filenames]

def opencv_load_images(filenames: List) -> List:
    '''
    Load images cv2.imread function (BGR)
    '''
    return [cv2.imread(filename) for filename in filenames]

# TODO Create two sorted lists with the paths of all images in the data/source folder using glob
source_paths = sorted(glob.glob("../data/source/*"))

# Cargar las imágenes utilizando ambas funciones
imageio_images = imageio_load_images(source_paths)
opencv_images = opencv_load_images(source_paths)

# Mostrar las imágenes cargadas con OpenCV para verificar (este es solo un ejemplo de impresión)
output_folder = "../data/partB"
os.makedirs(output_folder, exist_ok=True)
# Guardar la última imagen de cada lista en la carpeta 'partA'
# Usando OpenCV (necesitamos convertir la imagen cargada por imageio de RGB a BGR)
cv2.imwrite(os.path.join(output_folder, "imageio_image.jpg"), cv2.cvtColor(imageio_images[-1], cv2.COLOR_RGB2BGR))
cv2.imwrite(os.path.join(output_folder, "opencv_image.jpg"), opencv_images[-1])

C:\Users\jorge.moratalla\AppData\Local\Temp\ipykernel_16704\1006126513.py:8: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]


True

### **Tarea B.1.** Aplique `cv2.Canny()` a las imágenes de trabajo ajustando los hiperparámetros

In [11]:
# TODO Apply canny to the images, play with the thresholds to get a good result
def show_image(img: np.array, img_name: str = "Image"):
    cv2.imshow(img_name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

output_folder = "../data/partB"
os.makedirs(output_folder, exist_ok=True)

edge_imgs = []  # to store the canny edge images for later Hough transform

# 1st image

# Hyperparameters
low_threshold = 50
high_threshold = 150

# get the first image
img = copy.copy(opencv_images[0])

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(gray_img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)
# Display the image or save it as you like
show_image(edge_img, "Canny Geometry")

# 2nd image
low_threshold2 = 60
high_threshold2 = 200

img2 = copy.copy(opencv_images[1])

gray_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

edge_img2 = cv2.Canny(gray_img2, low_threshold2, high_threshold2)

edge_imgs.append(edge_img2)

show_image(edge_img2, "Canny Football")

### **Tarea B.2.** Implemente `draw_lines()` para pintar las lineas sobre cada imagen

In [12]:
# TODO Draw the lines on the images. A line is a tuple of 4 integers (x1, y1, x2, y2) where (x1, y1) and (x2, y2) are the coordinates of the two points of the line.
def draw_lines(img, lines, color, thickness):
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(img, (x1, y1), (x2, y2), color, thickness)
    return img

### **Tarea B.3.** Aplique Hough con `cv2.HoughLinesP()` a las imágenes de trabajo para extraer líneas y afine los hiperparámetros

In [13]:
# TODO Apply the hough transform to the images, play with the parameters to get a good result

# 1st image

# Define the hough transform parameters
rho = 1
theta = np.pi/180
threshold = 40
min_line_length = 15
max_line_gap = 20

# Get the edge image
edges = edge_imgs[0]

# Apply the hough transform
lines = cv2.HoughLinesP(edges, rho, theta, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)

# Draw the lines on the image (on the original image, make sure to get a copy, as draw_lines modifies the image)
img_with_lines_geometry = draw_lines(copy.copy(opencv_images[0]), lines, color=(0, 255, 0), thickness=2)

# Show the image or save it as you like
show_image(img_with_lines_geometry, "Hough Transform - Geometry")

# 2nd image
rho2 = 1
theta2 = np.pi/180
threshold2 = 40
min_line_length2 = 20
max_line_gap2 = 10

# Get the edge image
edges2 = edge_imgs[1]

# Apply the hough transform
lines2 = cv2.HoughLinesP(edges2, rho2, theta2, threshold2, minLineLength=min_line_length2, maxLineGap=max_line_gap2)

# Draw the lines on the image (on the original image, make sure to get a copy, as draw_lines modifies the image)
img_with_lines_geometry2 = draw_lines(copy.copy(opencv_images[1]), lines2, color=(0, 255, 0), thickness=2)

# Show the image or save it as you like
show_image(img_with_lines_geometry2, "Hough Transform - Geometry")

### **Problema B.1.** Repita el procedimiento para extraer las líneas de las dos imágenes restantes

In [14]:
# TODO Homework
# TODO Apply canny to the images, play with the thresholds to get a good result


# 3rd image
img = opencv_images[2]

# Hyperparameters
low_threshold = 60
high_threshold = 200

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
show_image(edge_img)



# get the fourth image
img = opencv_images[3]

# Hyperparameters
low_threshold = 60
high_threshold = 230

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
show_image(edge_img)


In [15]:
# TODO Homework

# 3rd image (opencv_images[2])
# Define the hough transform parameters
rho = 1
theta = np.pi / 180
threshold = 50
min_line_length = 20
max_line_gap = 2

# Get the edge image for the 3rd image
edges = edge_imgs[2]

# Apply the hough transform
lines = cv2.HoughLinesP(edges, rho, theta, threshold, min_line_length, max_line_gap)
print(lines)

# Draw the lines on the image (on the original image, make sure to get a deep copy to avoid modifying the original)
img_with_lines = draw_lines(copy.deepcopy(opencv_images[2]), lines, (0, 255, 0), thickness=3)

# Show the image or save it as you like
show_image(img_with_lines)

# 4th image (opencv_images[3])
rho = 1
theta = np.pi/180
threshold = 25
min_line_length = 5
max_line_gap = 35

# Get the edge image for the 4th image
edges = edge_imgs[3]

# Apply the hough transform
lines = cv2.HoughLinesP(edges, rho, theta, threshold, min_line_length, max_line_gap)
print(lines)

# Draw the lines on the image (on the original image, make sure to get a deep copy)
img_with_lines = draw_lines(copy.deepcopy(opencv_images[3]), lines, (0, 255, 0), thickness=3)

# Show the image or save it as you like
show_image(img_with_lines)

[[[451 497 644 497]]

 [[655 637 655  15]]

 [[515 360 647 360]]

 ...

 [[ 38 426  71 426]]

 [[249 426 305 426]]

 [[482 117 485 114]]]
[[[ 61 226 289 226]]

 [[ 66 250 284 250]]

 [[ 61  66 165  66]]

 [[ 63  39 287  39]]

 [[291  64 519  64]]

 [[415 224 519 224]]

 [[289 223 289  67]]

 [[519 223 519 146]]

 [[521 252 521  38]]

 [[290 144 413 144]]

 [[291 224 291 145]]

 [[292 146 413 146]]

 [[167 224 167 146]]

 [[ 58 252  58  39]]

 [[165 224 165  67]]

 [[ 61 224  61 146]]

 [[413 223 413 147]]

 [[415 223 415  66]]

 [[207  64 263  64]]

 [[337 226 393 226]]

 [[ 77  64 133  64]]

 [[418 226 474 226]]

 [[156  64 206  64]]

 [[168 224 288 224]]

 [[290  66 412  66]]

 [[413 136 413  80]]

 [[420  39 476  39]]

 [[291  67 291 114]]

 [[300 250 348 250]]

 [[ 61  97  61 144]]

 [[358 250 414 250]]

 [[519 101 519  66]]

 [[299  39 355  39]]

 [[418 250 474 250]]

 [[167  72 167 128]]

 [[191 144 232 144]]

 [[ 95 224 151 224]]

 [[416  66 465  66]]

 [[519 144 519 102]]

 [[4